# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Academia Matecaracha
email: contacto@matecaracha.com
description: >-
  Academia especializada en matemáticas con clases, retos y profesores expertos. ¡Descubre el poder de aprender con Matecaracha!
baseurl: "/matecaracha"
url: "https://matecaracha.github.io"
twitter_username: matecaracha
github_username: matecaracha

# Colores personalizados
primary_color: "#c00" # Rojo Matecaracha
background_color: "#000" # Negro
text_color: "#fff" # Blanco

# Logo
logo: "/assets/logo.png" # Coloca tu logo en esta ruta

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Información de la academia
materias:
  - Matemáticas Básicas
  - Álgebra
  - Geometría
  - Cálculo
  - Estadística
  - Lógica Matemática
profesores:
  - nombre: Ana Torres
    especialidad: Matemáticas Básicas
  - nombre: Luis Gómez
    especialidad: Álgebra y Geometría
  - nombre: Carla Ruiz
    especialidad: Cálculo y Estadística
creativo:
  titulo: "Desafío Matecaracha"
  descripcion: "Cada semana, un reto matemático para los estudiantes, con premios simbólicos y reconocimiento en la web."

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
