name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # O la versión que necesites
          bundler-cache: true # Instala dependencias y las guarda en caché

      - name: Build Jekyll Site
        run: bundle exec jekyll build --baseurl ${{ github.repository_name }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
